name: Question
description: Ask a question about DittoMation
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're happy to help!

        **Tip:** For general discussions, consider using [GitHub Discussions](https://github.com/OmPrakashSingh1704/DittoMation/discussions) instead.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context (what you're trying to do, what you've tried, etc.)
      placeholder: I'm trying to automate... and I'm not sure how to...

  - type: textarea
    id: code
    attributes:
      label: Relevant Code or Commands
      description: Share any relevant code, commands, or configuration.
      render: python

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked the [documentation](https://omprakashsingh1704.github.io/DittoMation/)
          required: true
        - label: I have searched existing issues and discussions
          required: true
